---
ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    base_link_frame: base_link
    world_frame: map  

    imu0: /RaspbotV2/imu
    imu0_config: [false, false, false,  # Position (X, Y, Z) -> Not available
                  true, true, false,     # Orientation (Roll, Pitch, Yaw) -> Use all
                  false, false, false,    # Linear velocity (X, Y, Z) -> Estimate X, Y
                  false, false, true,   # Angular velocity (X, Y, Z) -> Use Z for yaw rate
                  true, false, false]    # Linear acceleration (X, Y, Z) -> Use X, Y
